### PR TITLE
Attempt to correct the issue #50 (Encryption fails with perl-5.22.1 on HP-UX-ia64)

### PR DESCRIPTION
**Pull request by mazurin**
unpack("L", ...) is platform dependent, it may cause this issue. Replaced with unpack("V", ...)

### CODE REVIEW

**Comment by Tux** [comment]
Maybe for future changes "L<" may be clearer than "V"

**Comment by mazurin** [comment]
@Tux I'm not sure that "L<" is always 32 bit length

**Comment by Tux** [comment]
http://tux.nl/Talks/Data-Peek/pack.html shows you how pack stores the data

**Comment by doy** [comment]
Thanks!

**Pull request merged**
